# Written by: Erick Cobos T (erick.cobos@epfl.ch)
# Date: 10-03-2014

# Usage: R -f plotTopicDistribution.R --args stem.tdist

# This script receives a .tdist file generated by DCA and plots the topic distribution over the entire corpus
# Some changes can be made to select only a subset of the corpus. These changes will be done on demand
# This script should be run after running: "mpupd -m 0 stem > stem.tdist", where stem is the name of the input,
# e.g. 20news, abstracts, neuroscience, etc
# Output(.pdf): A histogram plot of the topic distribution

# Read arguments
a <- commandArgs(trailingOnly=TRUE)
fileName <- a[1]
xAxisSpace = 10

# Read data
d <- read.table(file=fileName, header=FALSE, row.names=1)

#Calculate probability over entire corpus
frequency = apply(d,2,sum)
probability = frequency/sum(frequency)

# Make the plot
pdf("topicDistribution.pdf")
plot(probability, xlab="Topic Number",ylab="Probability", type='h', lwd=3, xaxt='n')
axis( 1, at=seq(from = 0, to = length(probability), by = xAxisSpace) )
dev.off()
